//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doodlelu2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLKULLANICI
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLKULLANICI()
        {
            this.TBLTOPLANTI = new HashSet<TBLTOPLANTI>();
        }
    
        public string kullaniciad { get; set; }
        public string mail { get; set; }
        public string sifre { get; set; }
        public virtual bool rememberme { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLTOPLANTI> TBLTOPLANTI { get; set; }
    }
}
