//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Doodlelu2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLTOPLANTI
    {
        public string topad { get; set; }
        public string toptarih1 { get; set; }
        public string platform { get; set; }
        public string davetli1 { get; set; }
        public string davetli2 { get; set; }
        public string davetli3 { get; set; }
        public string davetli4 { get; set; }
        public string davetli5 { get; set; }
        public string davetciad { get; set; }
        public Nullable<int> davetli { get; set; }
        public string notlar { get; set; }
    
        public virtual TBLKULLANICI TBLKULLANICI { get; set; }
    }
}
